### ISSUE TITLE
Can you add support for ubuntu 18.04?

### ISSUE THREAD

**Issue by denisgolius** [nsz32/docklike-plugin#52] opened 2020-12-08 05:09 UTC
Hello!
Can you add support for ubuntu 18.04?

```
root@ryzen:/tmp/docklike-plugin# ./autogen.sh
xdt-autogen: This version of xdt-autogen (4.12.0) is too old.
             Version 4.14.0 or greater is required.
```

**Comment by nsz32** [comment] 2020-12-09 03:02
Duplicate of #41 , check it for compilation instructions.
Maybe should we include this changes in the repo ?

**Comment by gsantner** [comment] 2020-12-22 22:18
@nsz32 I made a PR at #66 that covers both issues. With it the plugin runs on my XFCE 4.12 + Ubuntu 18.04.

**Closed** 2020-12-26 11:43 UTC
Labels: good first issue
